language: node_js

branches:
  only:
    - master

script:
    - ls -al style.css
    - ls -al bootstrap/tsumugi.css
    - ls -al bootstrap/tsumugi.css
    - ls -al bower_components/bootstrap/dist/css/bootstrap.min.css
    - ls -al bower_components/bootstrap/dist/js/bootstrap.min.js
    - ls -al bower_components/tether/dist/js/tether.min.js
    - ls -al js/navigation.js
    - ls -al js/skip-link-focus-fix.js

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/littlebirdjp/tsumugi.git
  - secure: "RSFk7zAzoCJzkCWaJs3Qfcvflc0ncsUMn1AxrA4uDQ6V4Bmoq+qXvTKLJdYOd3DSSZ+5HKABVSmyZVpGzPAkJPLeRor446LebSxzu5D0pGoj/dwipq6KJECslgZcVFwHXtFoILV03q66bmNqHzqXTbkk5otKDopS8xvvG0VmXJ20o6P3+UT941d7PzW0J42rLcychldXh4h2uzpNu2zglOUJJ3begCVI6jg30+hBSEMsYCUDu11BrTv+NQN5WnAz1R2qnYAM075o9RIumphJnVpm7o2CAxQnvyfGp9h6teeT6hWZ/fBJoQfFEktawNuQiv8e8TdWIxpuCSwdmcRrasgg5disYaStmV1TtrAMYYFcBVvzoIIvcgWObsGTu/EhHo64yuH5XSIC99eupD/16yMjXYyGEpOmSOmfdtvGBa4YWPB1oalpOQ3n9F2UGrURHIT3Lp6R7oOVyjDrjVj40ON5/pRB2k14tweTttlBfw00sALqkf7f8ACkxOywRDgj6OsunQQYJHNLS4DKDSfdlbn8EqTZcvdTePxTfxBljR5fkjlrIXIytin5n+h6J1vdoy0S0D9oG8AOSpIInbY178U8LpoNXByaCqnw8keJVynRVYcIfW4uLo+gBs2abe3KRB0wQ/e7kg3UHGM777LyAS68Nl+UNdp3XjcaLCkFRPg="
